### PR TITLE
Cat function

### PR DESCRIPTION
**Pull request by ooaj**
Hi. 

Unfortunately had to add two commits rather than one and I wasn't really sure if I should add the example in `Examples` folder, so I did not, but a simple example is as follows

```
double A[2 * 3] = {1, 2, 3,
 		4, 5, 6};
double B[2 * 4] = {7, 8, 9, 6,
 		1, 2, 3, 5};
double C[2 * 7] = {0};

cat(2, A, B, C, 2, 3, 2, 4, 2, 7);
print(C, 2, 7);
```

### CODE REVIEW

**Comment by DanielMartensson** [comment]
Very good. But i think it would be better if you did this. I replaced the `uint16_t` with `uint8_t` and you had double place between `uint16_t  rowA`

`void cat(uint8_t dim, float A[], float B[], float C[], uint16_t row_a,
		uint16_t column_a, uint16_t row_b, uint16_t column_b, uint16_t row_c, uint16_t column_c)`

Just as this function. I like if there are same name for the arguments.
`void insert(float A[], float B[], uint16_t row_a, uint16_t column_a, uint16_t column_b, uint16_t startRow_b, uint16_t startColumn_b);`

And I need to have an example too. Have a look at this function.
https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Documents/Examples/Miscellaneous/insert.txt

By the way. Do you really need `dim` variable? Can't you use some `if-statements` to compute the `dim` variable instead because we know the dimensions of `A, B, C` matrix ? Much easier to use =)

**Comment by DanielMartensson** [comment]
Assume that you have a matrix `A[3x2]` and a matrix `B[3x2]` and you want to concat these two into `C[3x4]`, then `dim` variable can be found because it's only one solution here `[A B] = C` and not `[A;B] =/= C`

If `C` would be `[6x2]`, then the matrices `A` and `B` would be concatinated as `[A;B] = C`

If `A` and `B` would not fit into `C`, the `cat` function will return `false` as it was declared `bool cat(your arguments here)`.

What do you think about that?

**Comment by ooaj** [comment]
> Very good. But i think it would be better if you did this. I replaced the `uint16_t` with `uint8_t` and you had double place between `uint16_t rowA`
> 
> `void cat(uint8_t dim, float A[], float B[], float C[], uint16_t row_a, uint16_t column_a, uint16_t row_b, uint16_t column_b, uint16_t row_c, uint16_t column_c)`
> 
I edited the header and source file accordingly. 

> And I need to have an example too. Have a look at this function. https://github.com/DanielMartensson/CControl/blob/master/src/CControl/Documents/Examples/Miscellaneous/insert.txt
> 
I will add the example ASAP when I'm available. 
> By the way. Do you really need `dim` variable? Can't you use some `if-statements` to compute the `dim` variable instead because we know the dimensions of `A, B, C` matrix ? Much easier to use =)

In this case, I think you are right that we do not really need `dim`. However, I think we should still implement it because: 

1. The syntax is much similar to MATLAB this way. 
2. In case assert check is removed in the future, consider the case where A is `3x3` and B is `3x3`, however matrix C's dimensions might be much larger than both A and B, let's say `12x12`, I think we should leave it to the user. What do you think?

**Comment by DanielMartensson** [comment]
> 

Good!

So if I have an matrix `A[3x2]` and `B[3x2]` and I want to implement it into a matrix `C[12]`, then if I select `dim = 1`, then I will get the matrix `C[3x4]` and if I select `dim = 2`, then I will have the matrix `C[6x2]` ?

If, yes. Then I will accept the request.

**Comment by DanielMartensson** [comment]
Sorry! I tried out your code and it was some bugs into it. 

I think it was the first pull request you made. Can you do a new pull request again?

**Pull request merged**
